spring:
  datasource:
    url: jdbc:mysql://10.115.1.29:3306/live_class?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: beeschool
    password: beeschool

mybatis:
  configuration:
    map-underscore-to-camel-case: true

mapper:
  not-empty: false
  identity: MYSQL
  use-simple-type: false

#以下配置不要在线上开启或者修改级别
logging:
  level:
    com.fengxiao.auto.example: DEBUG
