spring:
  datasource:
    #url: 数据库配置
    #username: 数据库配置
    #password: 数据库配置

mybatis:
  configuration:
    map-underscore-to-camel-case: true

mapper:
  not-empty: false
  identity: MYSQL
  use-simple-type: false

logging:
  level:
    com.freeperch.auto.example: INFO
